#!/bin/bash

echo "Atualizando o servidor..."
apt-get uptdate
apt-get upgrade -y
apt-get install apache2 -y
apt-get install unzip -y


echo "Baixando e copiando os arquivos da aplicação..."

cd /tmp
cd /linux-site-dio
cd -R * /var/www/html/
